# Generated by Django 5.2.7 on 2025-11-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('terms', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_courseallocation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCoordinatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_assignment_actions', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to='departments.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_assignments', to='programs.program')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_assignments', to='terms.term')),
            ],
            options={
                'verbose_name': 'Course Coordinator Assignment',
                'verbose_name_plural': 'Course Coordinator Assignments',
                'db_table': 'course_coordinator_assignments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursecoordinatorassignment',
            unique_together={('coordinator', 'course', 'term')},
        ),
    ]
