# Generated by Django 5.2.1 on 2025-11-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('HOD', 'HOD'), ('CONVENER', 'Convener'), ('COORDINATOR', 'Coordinator'), ('FACULTY', 'Faculty'), ('AUDIT_TEAM', 'Audit Team')], max_length=50),
        ),
    ]
