# Generated by Django 4.2.7 on 2025-10-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('programs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department (for Convener, Coordinator, Supervisor, Evaluator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program (for Coordinator, Supervisor, Evaluator, Student)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='programs.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(help_text='National Identity Card Number (e.g 3130456789112)', max_length=11, unique=True, verbose_name='CNIC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CONVENER', 'Convener'), ('COORDINATOR', 'Coordinator'), ('SUPERVISOR', 'Supervisor'), ('EVALUATOR', 'Evaluator'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
