# Generated by Django 5.2.7 on 2025-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, help_text='Base64 encoded profile picture (max 5MB)', null=True),
        ),
    ]
