# Generated by Django 5.2.1 on 2025-11-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('CONVENER', 'Convener'), ('COORDINATOR', 'Coordinator'), ('FACULTY', 'Faculty'), ('AUDIT_TEAM', 'Audit Team'), ('AUDIT_MEMBER', 'Audit Member')], default='STUDENT', max_length=20),
        ),
    ]
