# Generated by Django 4.2.7 on 2025-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_department_user_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(help_text='National Identity Card Number (e.g 3130456789112)', max_length=13, unique=True, verbose_name='CNIC'),
        ),
    ]
