# Generated by Django 5.2.7 on 2025-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CONVENER', 'Convener'), ('COORDINATOR', 'Coordinator'), ('FACULTY', 'Faculty'), ('SUPERVISOR', 'Supervisor'), ('EVALUATOR', 'Evaluator'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
