# Generated by Django 5.2.7 on 2025-10-10 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_courseallocation_unique_together'),
        ('departments', '0001_initial'),
        ('faculty', '0002_faculty_faculty_id'),
        ('programs', '0001_initial'),
        ('terms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('RETURNED', 'Returned for Revision'), ('APPROVED_COORDINATOR', 'Approved by Coordinator'), ('UNDER_AUDIT', 'Under Audit'), ('AUDIT_COMPLETED', 'Audit Completed'), ('SUBMITTED_HOD', 'Submitted to HOD'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_notes', models.TextField(blank=True)),
                ('convenor_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('audit_completed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True)),
                ('consolidated_pdf', models.FileField(blank=True, null=True, upload_to='consolidated_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_generation_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('completeness_check_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_folders', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='courses.course')),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='courses.courseallocation')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='departments.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='faculty.faculty')),
                ('hod_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_folders', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='programs.program')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='terms.term')),
            ],
            options={
                'verbose_name': 'Course Folder',
                'verbose_name_plural': 'Course Folders',
                'db_table': 'course_folders',
                'ordering': ['-created_at'],
                'unique_together': {('course_allocation', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final Exam')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('question_paper', models.FileField(blank=True, max_length=500, null=True, upload_to='assessments/questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('model_solution', models.FileField(blank=True, max_length=500, null=True, upload_to='assessments/solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('sample_scripts', models.FileField(blank=True, max_length=500, null=True, upload_to='assessments/scripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course_folders.coursefolder')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments',
                'ordering': ['assessment_type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='FolderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('TITLE_PAGE', 'Title Page'), ('COURSE_OUTLINE', 'Course Outline'), ('COURSE_LOG', 'Course Log'), ('ATTENDANCE', 'Attendance Record'), ('REFERENCE_BOOKS', 'Reference Books'), ('FINAL_RESULT', 'Final Result Document'), ('AUDIT_FEEDBACK', 'Audit Feedback'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=500, upload_to='folder_components/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_size', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='course_folders.coursefolder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder Component',
                'verbose_name_plural': 'Folder Components',
                'db_table': 'folder_components',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='course_folders.coursefolder')),
            ],
            options={
                'verbose_name': 'Folder Status History',
                'verbose_name_plural': 'Folder Status Histories',
                'db_table': 'folder_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('FOLDER_SUBMITTED', 'Folder Submitted'), ('FOLDER_APPROVED', 'Folder Approved'), ('FOLDER_RETURNED', 'Folder Returned'), ('AUDIT_ASSIGNED', 'Audit Assigned'), ('PDF_GENERATED', 'PDF Generated'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='course_folders.coursefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_submitted', models.BooleanField(default=False)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_file', models.FileField(blank=True, max_length=500, null=True, upload_to='audit_feedback/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('remarks', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_audits', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assignments', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assignments', to='course_folders.coursefolder')),
            ],
            options={
                'verbose_name': 'Audit Assignment',
                'verbose_name_plural': 'Audit Assignments',
                'db_table': 'audit_assignments',
                'unique_together': {('folder', 'auditor')},
            },
        ),
        migrations.CreateModel(
            name='CourseLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.IntegerField()),
                ('date', models.DateField()),
                ('duration', models.IntegerField(default=60)),
                ('topics_covered', models.TextField()),
                ('evaluation_instrument', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='course_folders.coursefolder')),
            ],
            options={
                'verbose_name': 'Course Log Entry',
                'verbose_name_plural': 'Course Log Entries',
                'db_table': 'course_log_entries',
                'ordering': ['lecture_number'],
                'unique_together': {('folder', 'lecture_number')},
            },
        ),
    ]
