# Generated by Django 5.2.1 on 2025-11-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0003_courselogentry_attendance_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditassignment',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='auditassignment',
            name='ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
