# Generated by Django 5.2.1 on 2025-11-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0005_auditteam_auditteammember'),
    ]

    # Simplified: directly delete dependent model first, then parent.
    # Removing individual fields / altering unique_together is unnecessary if the whole model is dropped.
    operations = [
        migrations.DeleteModel(
            name='AuditTeamMember',
        ),
        migrations.DeleteModel(
            name='AuditTeam',
        ),
    ]
