# Generated by Django 5.2.7 on 2025-11-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0006_remove_auditteammember_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefolder',
            name='outline_content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
