# Generated by Django 5.2.7 on 2025-11-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0007_coursefolder_outline_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefolder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed - Ready to Submit'), ('SUBMITTED', 'Submitted to Coordinator'), ('APPROVED_COORDINATOR', 'Approved by Coordinator'), ('REJECTED_COORDINATOR', 'Rejected by Coordinator'), ('ASSIGNED_TO_CONVENER', 'Assigned to Convener'), ('UNDER_AUDIT', 'Under Audit Review'), ('AUDIT_COMPLETED', 'Audit Completed'), ('REJECTED_BY_CONVENER', 'Rejected by Convener'), ('SUBMITTED_TO_HOD', 'Submitted to HOD'), ('APPROVED_BY_HOD', 'Approved by HOD (Final)'), ('REJECTED_BY_HOD', 'Rejected by HOD')], default='DRAFT', max_length=30),
        ),
    ]
