# Generated by Django 5.2.7 on 2025-11-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0010_coursefolder_coordinator_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefolder',
            name='coordinator_decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='coordinator_remarks',
            field=models.TextField(blank=True),
        ),
    ]
