# Generated by Django 5.2.7 on 2025-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0013_cleanup_orphaned_file_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefolder',
            name='audit_member_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
