# Generated by Django 5.2.7 on 2025-10-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('faculty', '0002_faculty_faculty_id'),
        ('programs', '0001_initial'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='departments.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='faculty.faculty')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_allocations', to='programs.program')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='terms.term')),
            ],
            options={
                'verbose_name': 'Course Allocation',
                'verbose_name_plural': 'Course Allocations',
                'db_table': 'course_allocations',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'section', 'term')},
            },
        ),
    ]
