# Generated by Django 5.2.7 on 2025-10-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseallocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together=set(),
        ),
    ]
