# Generated by Django 5.2.1 on 2025-11-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefolder',
            old_name='convenor_assigned_at',
            new_name='convener_assigned_at',
        ),
        migrations.RenameField(
            model_name='coursefolder',
            old_name='hod_approved_at',
            new_name='hod_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='coursefolder',
            name='hod_approved_by',
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='audit_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='convener_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convener_assigned_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='convener_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='hod_decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='hod_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='hod_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_reviewed_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursefolder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Coordinator'), ('APPROVED_COORDINATOR', 'Approved by Coordinator'), ('REJECTED_COORDINATOR', 'Rejected by Coordinator'), ('ASSIGNED_TO_CONVENER', 'Assigned to Convener'), ('UNDER_AUDIT', 'Under Audit Review'), ('AUDIT_COMPLETED', 'Audit Completed'), ('REJECTED_BY_CONVENER', 'Rejected by Convener'), ('SUBMITTED_TO_HOD', 'Submitted to HOD'), ('APPROVED_BY_HOD', 'Approved by HOD (Final)'), ('REJECTED_BY_HOD', 'Rejected by HOD')], default='DRAFT', max_length=30),
        ),
    ]
