# Generated by Django 5.2.1 on 2025-11-02 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0002_rename_convenor_assigned_at_coursefolder_convener_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselogentry',
            name='attendance_sheet',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attendance_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'csv'])]),
        ),
    ]
