# Generated by Django 5.2.7 on 2025-11-13 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0008_alter_coursefolder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineContentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_snapshots', to='course_folders.coursefolder')),
            ],
            options={
                'verbose_name': 'Outline Content Snapshot',
                'verbose_name_plural': 'Outline Content Snapshots',
                'db_table': 'outline_content_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
