# Generated by Django 5.2.7 on 2025-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0009_outlinecontentsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefolder',
            name='coordinator_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
