# Generated by Django 5.2.7 on 2025-11-23 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0011_coursefolder_coordinator_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefolder',
            name='clo_assessment_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='clo_assessments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='course_result_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='course_results/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='project_report_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='project_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='foldercomponent',
            name='component_type',
            field=models.CharField(choices=[('TITLE_PAGE', 'Title Page'), ('COURSE_OUTLINE', 'Course Outline'), ('COURSE_LOG', 'Course Log'), ('ATTENDANCE', 'Attendance Record'), ('REFERENCE_BOOKS', 'Reference Books'), ('FINAL_RESULT', 'Final Result Document'), ('MODEL_SOLUTION', 'Model Solution'), ('AUDIT_FEEDBACK', 'Audit Feedback'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
