# Generated by Django 5.2.7 on 2025-11-28 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_folders', '0014_coursefolder_audit_member_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefolder',
            name='folder_review_report_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='folder_review_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
